--@diagnostic disable: undefined-global
local lush = require("lush")
local colours = require('falcon.colours')
local styles = require('falcon.styles')
local zen = require('falcon.zen')

local p = lush(function(injected_functions)
    local sym = injected_functions.sym
    return {
        TSAnnotation                {},
        TSAttribute                 {},
        TSBoolean                   {},
        TSCharacter                 {},
        TSCharacterSpecial          {}, -- Special characters.
        TSComment                   {},
        TSConditional               {},
        TSConstBuiltin              {},
        TSConstMacro                {},
        TSConstant                  {},
        TSConstructor               {},
        TSDanger                    {},
        TSDebug                     {},
        TSDefine                    {},
        TSEmphasis                  {},
        TSEnvironment               {},
        TSEnvironmentName           {},
        TSError                     {},
        TSException                 {},
        TSField                     {},
        TSFloat                     {},
        TSFuncBuiltin               {},
        TSFuncMacro                 {},
        TSFunction                  {},
        TSInclude                   {},
        TSKeyword                   {},
        TSKeywordFunction           {},
        TSOperator                  {},
        TSKeywordOperator           {},
        TSKeywordReturn             {},
        TSLabel                     {},
        TSLiteral                   {},
        TSMath                      {},
        TSMethod                    {},
        TSNamespace                 {},
        TSNone                      {},
        TSNote                      {},
        TSNumber                    {},
        TSParameter                 {},
        TSParameterReference        {},
        TSProperty                  {},
        TSPunctBracket              {},
        TSPunctDelimiter            {},
        TSPunctSpecial              {},
        TSRepeat                    {},
        TSStrike                    {},
        TSString                    {},
        TSStringEscape              {},
        TSStringRegex               {},
        TSStringSpecial             {},
        TSStrong                    {},
        TSStructure                 {},
        TSSymbol                    {},
        TSTag                       {},
        TSTagAttribute              {},
        TSTagDelimiter              {},
        TSText                      {},
        TSTextReference             {},
        TSTitle                     {},
        TSType                      {},
        TSTypeBuiltin               {},
        TSURI                       {},
        TSUnderline                 {},
        TSVariable                  {},
        TSVariableBuiltin           {},
        TSWarning                   {},
        sym('@annotation')          {},
        sym('@attribute')           {},
        sym('@boolean')             {},
        sym('@conditional')         {zen.Conditional},
        sym('@keyword')             {zen.Keyword},
        sym('@keyword.function')    {zen.Keyword},
        sym('@function')            {},
        sym('@function.call')       {},
        sym('@function.builtin')    {sym("@keyword")},
        sym('@include')             {sym("@keyword")},
        sym('@method')              {},
        sym('@punctuation')         {fg = colours.mid_gray},
        sym('@punctuation.bracket') {sym("@punctuation")},
        sym('@property')            {},
        sym('@repeat')              {sym("@keyword")},
        sym('@tag')                 {sym("@keyword")},
        sym('@tag.attribute')       {},
        sym('@tag.delimiter')       {sym("@punctuation")},
        sym('@text.title')          {zen.Normal},
        sym('@variable.builtin')    {sym("@keyword")},
    }
end)

return p
