--@diagnostic disable: undefined-global
local lush = require("lush")
local colours = require('falcon.colours')
local classic = require('falcon.classic')
local base_ui = require('falcon.base_ui')
local styles = require('falcon.styles')

local p = lush(function(injected_functions)
    local sym = injected_functions.sym
    return {
        TSAnnotation         {},
        TSAttribute          {},
        TSBoolean            {},
        TSCharacter          {},
        TSCharacterSpecial   {} , -- Special characters.
        TSComment            {},
        TSConditional        {fg = colours.blue_gray},
        TSConstBuiltin       {},
        TSConstMacro         {},
        TSConstant           {},
        TSConstructor        {},
        TSDanger             {},
        TSDebug              {},
        TSDefine             {},
        TSEmphasis           {},
        TSEnvironment        {},
        TSEnvironmentName    {},
        TSError              {},
        TSException          {},
        TSField              {},
        TSFloat              {},
        TSFuncBuiltin        {},
        TSFuncMacro          {},
        TSFunction           {},
        TSInclude            {},
        TSKeyword            {},
        TSKeywordFunction    {},
        TSOperator           {},
        TSKeywordOperator    {},
        TSKeywordReturn      {},
        TSLabel              {},
        TSLiteral            {},
        TSMath               {},
        TSMethod             {},
        TSNamespace          {},
        TSNone               {},
        TSNote               {},
        TSNumber             {},
        TSParameter          {},
        TSParameterReference {},
        TSProperty           {},
        TSPunctBracket       {},
        TSPunctDelimiter     {},
        TSPunctSpecial       {},
        TSRepeat             {},
        TSStrike             {gui = styles.strikethrough},
        TSString             {},
        TSStringEscape       {},
        TSStringRegex        {},
        TSStringSpecial      {},
        TSStrong             {},
        TSStructure          {},
        TSSymbol             {},
        TSTag                {},
        TSTagAttribute       {},
        TSTagDelimiter       {},
        TSText               {},
        TSTextReference      {},
        TSTitle              {},
        TSType               {},
        TSTypeBuiltin        {},
        TSURI                {},
        TSUnderline          {gui = styles.underline},
        TSVariable           {},
        TSVariableBuiltin    {},
        TSWarning            {},
        sym('@conditional')  {gui = styles.italic},
        sym('@keyword')      {gui = styles.bold},
        sym('@punctuation')  {fg = colours.mid_gray},
        sym('@repeat')       {sym("@keyword")},
        sym('@include')      {sym("@keyword")},
    }
end)

return p
