--@diagnostic disable: undefined-global
local lush = require("lush")
local colours = require('falcon.colours')
local styles = require('falcon.styles')

local p = lush(function(injected_functions)
    local sym = injected_functions.sym
    return {
        TSAnnotation          {},
        TSAttribute           {},
        TSBoolean             {},
        TSCharacter           {},
        TSCharacterSpecial    {} , -- Special characters.
        TSComment             {},
        TSConditional         {},
        TSConstBuiltin        {},
        TSConstMacro          {},
        TSConstant            {},
        TSConstructor         {},
        TSDanger              {},
        TSDebug               {},
        TSDefine              {},
        TSEmphasis            {},
        TSEnvironment         {},
        TSEnvironmentName     {},
        TSError               {},
        TSException           {},
        TSField               {},
        TSFloat               {},
        TSFuncBuiltin         {},
        TSFuncMacro           {},
        TSFunction            {},
        TSInclude             {},
        TSKeyword             {},
        TSKeywordFunction     {},
        TSOperator            {},
        TSKeywordOperator     {},
        TSKeywordReturn       {},
        TSLabel               {},
        TSLiteral             {},
        TSMath                {},
        TSMethod              {},
        TSNamespace           {},
        TSNone                {},
        TSNote                {},
        TSNumber              {},
        TSParameter           {},
        TSParameterReference  {},
        TSProperty            {},
        TSPunctBracket        {},
        TSPunctDelimiter      {},
        TSPunctSpecial        {},
        TSRepeat              {},
        TSStrike              {},
        TSString              {},
        TSStringEscape        {},
        TSStringRegex         {},
        TSStringSpecial       {},
        TSStrong              {},
        TSStructure           {},
        TSSymbol              {},
        TSTag                 {},
        TSTagAttribute        {},
        TSTagDelimiter        {},
        TSText                {},
        TSTextReference       {},
        TSTitle               {},
        TSType                {},
        TSTypeBuiltin         {},
        TSURI                 {},
        TSUnderline           {},
        TSVariable            {},
        TSVariableBuiltin     {},
        TSWarning             {},
        sym('@boolean')       {gui = styles.italic},
        sym('@conditional')   {gui = styles.italic},
        sym('@function')      {},
        sym('@include')       {sym("@keyword")},
        sym('@keyword')       {fg = colours.mid_gray_alt, gui = styles.bold},
        sym('@method')        {},
        sym('@punctuation')   {fg = colours.mid_gray},
        sym('@repeat')        {sym("@keyword")},
        sym('@tag')           {sym("@keyword")},
        sym('@tag.attribute') {},
        sym('@text.title')    {fg = colours.normal_gray},
    }
end)

return p
