local lush = require('lush')
local colors = require('falcon.colors')
local hsluv = lush.hsluv

local styles = {
  italic = "italic",
  bold = "bold",
  underline = "underline",
  inverse = "inverse",
  undercurl = "undercurl",
  invert_signs = "",
  invert_selection = "inverse",
  invert_tabline = "",
  italic_comments = "italic",
  italic_booleans = "NONE",
  italic_strings = "NONE"
}

local theme = lush(function()
  return {
    -- Base UI
    ColorColumn {bg = colors.inactive_bg},
    Conceal { },
    Cursor {bg = colors.mid_gray},
    CursorIM { },
    CursorColumn {bg = colors.blue_darkest_gray},
    CursorLine {bg = colors.blue_dark_gray},
    CursorLineNr {fg = colors.normal_gray, bg = colors.blue_dark_gray},
    Directory {fg = colors.blue_gray},
    DiffAdd {bg = colors.off_green},
    DiffChange {bg = colors.off_blue},
    DiffDelete {bg = colors.off_red},
    DiffText {bg = colors.off_green},
    ErrorMsg {fg = colors.red},
    VertSplit {fg = colors.mid_gray},
    Folded {fg = colors.mid_gray, bg = colors.darker_gray},
    FoldColumn {fg = colors.mid_gray, bg = colors.darker_gray},
    SignColumn {fg = colors.blue_gray},
    IncSearch {fg = colors.bg_, bg = colors.br_blue, gui = styles.bold},
    LineNr {fg = colors.mid_dark_gray},
    MatchParen {fg = colors.br_tan, gui = styles.bold},
    ModeMsg {},
    MoreMsg {},
    NonText {fg = colors.dark_gray, bg = colors.bg_},
    Normal {fg = colors.normal_gray, bg = colors.bg_},
    PMenu {fg = colors.mid_gray_alt, bg = colors.blue_dark_float},
    PMenuSel {fg = colors.black, bg = colors.yellow},
    PmenuSbar {fg = colors.normal_gray},
    PmenuThumb {fg = colors.light_gray},
    Question {fg = colors.light_gray},
    Search {fg = colors.br_blue, gui = styles.underline .. ',' .. styles.bold},
    SpecialKey {fg = colors.mid_gray},
    SpellBad {bg = colors.purple_dark_gray, gui = styles.underline},
    SpellLocal {bg = colors.purple_dark_gray, gui = styles.underline},
    SpellCap {bg = colors.purple_dark_gray, gui = styles.undercurl},
    SpellRare {bg = colors.purple_dark_gray, gui = styles.underline},
    StatusLine {fg = colors.mid_gray, bg = colors.status},
    StatusLineNC {fg = colors.mid_gray, bg = colors.dark_gray},
    TabLine {fg = colors.mid_gray, bg = colors.dark_gray},
    TabLineFill {bg = colors.darker_gray},
    TabLineSel {fg = colors.light_gray},
    Title {fg = colors.tan},
    Visual {fg = colors.light_gray, bg = colors.dark_indigo},
    VisualNOS {},
    WarningMsg {},
    WildMenu {fg = colors.bg_, bg = colors.yellow},

    -- Base syntax
    Comment {fg = colors.mid_gray, gui = styles.italic},
    Constant {fg = colors.normal_gray, gui = styles.bold},
    String {fg = colors.light_blue_gray},
    Character {String},
    Boolean {fg = colors.normal_gray, gui = styles.italic},
    Number {fg = colors.normal_gray},
    Float {Number},
    Identifier {fg = colors.blue_gray},
    Function {fg = colors.yellow},
    Conditional {fg = colors.yellow},
    Statement {fg = colors.blue_gray},
    Exception {Statement},
    Repeat {Statement},
    Label {Statement},
    Operator {fg = colors.orange},
    Keyword {fg = colors.yellow},
    PreProc {fg = colors.tan},
    Include {PreProc},
    Define {PreProc},
    Macro {PreProc},
    PreCondit {PreProc},
    Type {fg = colors.light_gray},
    StorageClass {Type},
    Structure {Type},
    Typedef {Type},
    Special {fg = colors.orange},
    SpecialChar {Special},
    Tag {Special},
    Delimiter {fg = colors.light_gray},
    SpecialComment {Special},
    Debug {Special},
    Underlined {fg = colors.blue_gray, gui = styles.underline},
    Ignore {},
    Error {},
    Todo {fg = colors.bg_, bg = colors.tan, gui = styles.italic},
    QuickFixLine {fg = colors.br_blue, bg = colors.dark_gray},
    Bold {gui = styles.bold},
    Italic {gui = styles.italic},

    -- Newer items
    lCursor { },
    EndOfBuffer {NonText}, -- Filler lines (~) after the end of the buffer. By default, this is highlighted like |hl-NonText|.
    FloatBorder {fg = colors.dark_gray, bg = colors.blue_dark_float2},
    MsgArea      { }, -- Area for messages and cmdline
    MsgSeparator { }, -- Separator for scrolled messages, `msgsep` flag of 'display'
    TermCursor   { }, -- Cursor in a focused terminal
    TermCursorNC { }, -- Cursor in an unfocused terminal
    Substitute   { }, -- |:substitute| replacement text highlighting
    NormalFloat  {bg = colors.blue_dark_float2}, -- Normal text in floating windows. NormalNC     { }, -- normal text in non-current windows
    Whitespace   { }, -- "nbsp", "space", "tab" and "trail" in 'listchars'
    Winseparator { }, -- Separator between window splits. Inherts from |hl-VertSplit| by default, which it will replace eventually.

    -- LSP
    LspDiagnosticsDefaultError {fg = colors.mid_red},
    LspDiagnosticsDefaultWarning {fg = colors.mid_yellow},
    LspDiagnosticsDefaultInformation {fg = colors.mid_gray},
    LspDiagnosticsDefaultHint {fg = colors.dark_tan},
    LspReferenceRead {gui = styles.underline},
    LspReferenceText {gui = styles.underline},
    LspReferenceWrite {gui = styles.underline},
    LspDiagnosticsVirtualTextError {fg = colors.mid_red, gui = styles.italic},
    LspDiagnosticsVirtualTextWarning {fg = colors.mid_yellow, gui = styles.italic},
    LspDiagnosticsVirtualTextHint {fg = colors.dark_tan, gui = styles.italic},
    LspDiagnosticsVirtualTextInformation {fg = colors.mid_gray, gui = styles.italic},
    LspDiagnosticsUnderlineError {gui = styles.undercurl, guisp = colors.mid_red},
    LspDiagnosticsUnderlineWarning {gui = styles.undercurl, guisp = colors.mid_yellow},
    LspDiagnosticsUnderlineHint {gui = styles.undercurl, guisp = colors.dark_tan},
    LspDiagnosticsUnderlineInformation {gui = styles.undercurl, guisp = colors.mid_gray},
    DiagnosticSignError {fg = colors.mid_red},
    DiagnosticSignWarn {fg = colors.mid_yellow},
    DiagnosticSignInfo {fg = colors.mid_gray},
    DiagnosticSignHint {fg = colors.dark_tan},
    DiagnosticError {fg = colors.mid_red},
    DiagnosticWarn {fg = colors.mid_yellow},
    DiagnosticInfo {fg = colors.mid_gray},
    DiagnosticHint {fg = colors.dark_tan},
    ReferenceRead {gui = styles.underline},
    ReferenceText {gui = styles.underline},
    ReferenceWrite {gui = styles.underline},
    DiagnosticVirtualTextError {fg = colors.mid_red, gui = styles.italic},
    DiagnosticVirtualTextWarn {fg = colors.mid_yellow, gui = styles.italic},
    DiagnosticVirtualTextHint {fg = colors.dark_tan, gui = styles.italic},
    DiagnosticVirtualTextInfo {fg = colors.mid_gray, gui = styles.italic},
    DiagnosticUnderlineError {gui = styles.undercurl, guisp = colors.mid_red},
    DiagnosticUnderlineWarn {gui = styles.undercurl, guisp = colors.mid_yellow},
    DiagnosticUnderlineHint {gui = styles.undercurl, guisp = colors.dark_tan},
    DiagnosticUnderlineInfo {gui = styles.undercurl, guisp = colors.mid_gray},
  }
end)

return theme
